### ISSUE TITLE
gpio_to_serial error: invalid operands to binary

### ISSUE THREAD

**Issue by Khoa-NT** [aabadie/riot-apps#1]
Hi,

I got the errors when I run make all the project **gpio_to_serial** after I changed **static xtimer_ticks32_t last_press;**

```
/home/ntk/RIOT/riot-apps/gpio_to_serial/main.c: In function 'gpio_cb':
/home/ntk/RIOT/riot-apps/gpio_to_serial/main.c:55:26: error: invalid operands to binary < (have 'long unsigned int' and 'xtimer_ticks32_t {aka struct <anonymous>}')
     if (last_press + 100 < xtimer_now()) {
         ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~
/home/ntk/RIOT/riot-apps/gpio_to_serial/main.c:61:13: error: incompatible types when assigning to type 'uint32_t {aka long unsigned int}' from type 'xtimer_ticks32_t {aka struct <anonymous>}'
  last_press = xtimer_now();
             ^
/home/ntk/RIOT/riot-apps/gpio_to_serial/main.c: In function 'main':
/home/ntk/RIOT/riot-apps/gpio_to_serial/main.c:91:16: error: incompatible types when assigning to type 'uint32_t {aka long unsigned int}' from type 'xtimer_ticks32_t {aka struct <anonymous>}'
     last_press = xtimer_now();
                ^
/home/ntk/RIOT/Makefile.base:64: recipe for target '/home/ntk/RIOT/riot-apps/gpio_to_serial/bin/cc2650stk/gpio_to_uart/main.o' failed
make[1]: *** [/home/ntk/RIOT/riot-apps/gpio_to_serial/bin/cc2650stk/gpio_to_uart/main.o] Error 1
/home/ntk/RIOT/riot-apps/gpio_to_serial/../../Makefile.include:275: recipe for target 'all' failed
make: *** [all] Error 2
```

What should I do ?

**Comment by aabadie** [comment]
Hi and thanks for reporting this issue. For the moment, this code only works against RIOT 2016.10 release since 2017.01 introduced a major refactoring of the xtimer API.
This API change hasn't been backported to this project, I'll do that asap.

**Comment by aabadie** [comment]
@shaolinkhoa, I pushed an update that works will the latest master of RIOT. Can you try and let me know if it works for you ?

**Comment by Khoa-NT** [comment]
Hi,
I have fixed it too.
I changed xtimer_now() => **xtimer_now().ticks32** . And it works perfectly.

Thank you for creating those example project. 
I couldn't understand how to import and initial module in RIOT OS If I didn't  read your examples.

P/s: Do you have example about shell_commands + thread running together ?
I mean can I combine muti-thread(**gpio_to_serial**) + shell_command( **bt_config**)

**Comment by aabadie** [comment]
> Do you have example about shell_commands + thread running together ?
I mean can I combine muti-thread(gpio_to_serial) + shell_command( bt_config)

I'm not sure to understand: you would like to send a message to another thread from a shell command ? If it's that, I guess you can can call msg_send from the shell command function (see rx_cb function).

**Comment by Khoa-NT** [comment]
Yes, I would like to do that.

I'm sorry. I didn't read carefully.
**bt_config** has thread printer_pid in it.

**Comment by Khoa-NT** [comment]
Hi, 
One more question.

I don't have to call `uart_init(UART_INTERFACE, BAUDRATE, uart_cb, (void *)NULL)`, if I run `shell_run(shell_commands, line_buf, SHELL_DEFAULT_BUFSIZE);`  , right ?

I mean, I don't have to init **UART_DEV(0)** if I include **"shell.h"** , right ?

**Comment by aabadie** [comment]
> I mean, I don't have to init UART_DEV(0) if I include "shell.h" , right ?

If `UART_STDIO_DEV` is `UART_DEV(0)`, you are right. By default, RIOT uses `UART_DEV(0)`.

**Comment by Khoa-NT** [comment]
Hi,
It means that RIOT automatic initialize Uart , Led GPIO and other modules from the beginning ?
Or **shell.h** will automatic call `uart_stdio_init(UART_DEV(0))` when it was included ?

Cause I want to add Uart_Interrupt (just like `uart_cb()` in  **gpio_to_serial** example) to UART_DEV(0) but I can't find the place where the function `uart_stdio_init(UART_DEV(0))` was called in **bt_config** example.

When we use **shell_commands**, I don't know **Uart_Interrupt of UART_DEV(0)** is still available or it has been used for **shell_commands** ?

**Comment by aabadie** [comment]
In gpio_to_serial, the gpio is initialized from main here :https://github.com/aabadie/riot-apps/blob/master/gpio_to_serial/main.c#L80
You also need to import periph_gpio from the Makefile.

Regarding the shell, I think the stdio uart is automatically initialized from newlib : https://github.com/RIOT-OS/RIOT/blob/master/sys/uart_stdio/uart_stdio.c#L89

If you want to create your own callback function with UART_DEV(0), simply initialize it from the main, note that you won't be able to do that if you also use the shell (AFAIU).

**Comment by aabadie** [comment]
The initial problem is now fixed, I'll close this one.
