### ISSUE TITLE
gpio_to_serial wrong led status

### ISSUE THREAD

**Issue by Khoa-NT** [aabadie/riot-apps#2]
Hi,

While I testing with my cc2650 launchpad,I find 2 bugs in gpio_to_serial project:
+ [gpio_set(LED_GPIO)](https://github.com/aabadie/riot-apps/blob/master/gpio_to_serial/main.c#L78) means turn led on.

+ [print led status](https://github.com/aabadie/riot-apps/blob/master/gpio_to_serial/main.c#L95) should be `printf("Message received, LED is %s\n", gpio_read(LED_GPIO)? "ON" : "OFF");`
 
p/s: would you mind telling me:
+what does [SHELL_BUFSIZE](https://github.com/aabadie/riot-apps/blob/master/bt_config/main.c#L27) do in **bt_config** ? I can't find where it's used in shell.c . shell_commands.c
+What does  [msg_queue[8]](https://github.com/aabadie/riot-apps/blob/master/bt_config/main.c#L52) do  in **bt_config** ?
+Does RIOT OS is stable for cc2650 ? I read this [page](https://github.com/RIOT-OS/RIOT/wiki/Board%3A-CC2650STK) and it said that CC2650's Timers and RF core didn't work. I really want to test the RF of c2650

**Comment by aabadie** [comment]
Thanks for reporting. About the LED status, I guess this is because I tested that on an Atmel SAMR21 Xplained pro board where the LED status is inverted.

Regarding the CC2650, prefer asking directly on GitHub or the mailing list. You'll reach people more knowledgeable that I am with this platform. Cheers

**Comment by Khoa-NT** [comment]
Thank you.
I already sent mail to users@riot-os.org. Hope someone has example project about it

**Comment by aabadie** [comment]
I pushed an update that fixes the issues you reported here. About cc2650, I let the other RIOTers reply on the mailing list.
